services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "8000:80"
        environment:
            - APP_ENV=local
            - APP_DEBUG=true
            - DB_CONNECTION=mysql
            - DB_HOST=db
            - DB_PORT=3306
            - DB_DATABASE=laravel_test
            - DB_USERNAME=root
            - DB_PASSWORD=password
            - MIDTRANS_IS_PRODUCTION=false
            - MIDTRANS_SERVER_KEY=SB-Mid-server-xxx
            - MIDTRANS_CLIENT_KEY=SB-Mid-client-xxx
            - CLOUDINARY_API_SECRET=3lHG7ZkrWwm_gpH1USLtkIVBLMk
            - JWT_SECRET=7bv0hiZnsHSXfqIUFtQxOaBQro5FnSsNNcgBr09jhg00FW5qqnlKSkAJeUivTBUF
        volumes:
            - .:/var/www/html:cached
            - ./storage:/var/www/html/storage
        depends_on:
            - db
        networks:
            - laravel-network
        restart: unless-stopped
        deploy:
            resources:
                limits:
                    memory: 2G
                reservations:
                    memory: 1G

    db:
        image: mysql:8.0
        environment:
            MYSQL_DATABASE: laravel_test
            MYSQL_ROOT_PASSWORD: password
            MYSQL_USER: laravel
            MYSQL_PASSWORD: laravel
        ports:
            - "3306:3306"
        volumes:
            - mysql_data:/var/lib/mysql
            - ./database/init:/docker-entrypoint-initdb.d
        networks:
            - laravel-network
        restart: unless-stopped

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - "8080:80"
        environment:
            PMA_HOST: db
            PMA_USER: root
            PMA_PASSWORD: password
            PMA_PORT: 3306
        depends_on:
            - db
        networks:
            - laravel-network
        restart: unless-stopped

volumes:
    mysql_data:

networks:
    laravel-network:
        driver: bridge
